defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: /home/circleci/dgp

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - ~/dgp
          key: v1-repo-{{ .Revision }}
  release:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - run:
          name: release
          command: npx semantic-release || true
  pre-release:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}
      - run:
          name: pre-release
          command: npx semantish-prerelease --release-pr

workflows:
  version: 2
  test-and-publish:
    jobs:
      - install
      - release:
          requires:
            - install
          filters:
            branches:
              only: main
      - pre-release:
          requires:
            - install
          filters:
            branches:
              ignore: main
